### PR TITLE
K8 operator - jenkins file build

### PR DESCRIPTION
**Pull request by Jimbo4794**

### CODE REVIEW

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
rerun tests

**Comment by Jimbo4794** [comment]
DONT MERGE - WIP
Dont want the PR to push every PR was just testing build capabilites

**Review by Michael-Baylis — APPROVED** [review]

**Pull request merged**
