### PR TITLE
request from couchDB empty list

### PR DESCRIPTION
**Pull request by DianaSlepikaite**
Signed-off-by: Diana Slepikaite <d.slepikaite@gmail.com>

### CODE REVIEW

**Comment by DianaSlepikaite** [comment]
rerun tests

**Comment by DianaSlepikaite** [comment]
“rerun tests”

**Comment by DianaSlepikaite** [comment]
rerun tests

**Review by Michael-Baylis — APPROVED** [review]

**Comment by DianaSlepikaite** [comment]
rerun tests

**Pull request merged**
