### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jadecarino**
Signed-off-by: Jade Carino <jade.carino@ibm.com>

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-extensions-pr-189-s6ltt for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-extensions-pr-189-xt959 for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-extensions-pr-189-99srx for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-extensions-pr-189-65m2l for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-extensions-pr-189-nq46c for details

**Comment by techcobweb** [comment]
@jadecarino Don't know if you are aware of it or not, but you can create an empty commit ... useful for kicking off builds ...etc.
`git commit -m "empty on purpose to bump the build" --allow-empty`
(or something similar as that's off the top of my head).

**Comment by galasa-team** [comment]
Build successful

**Pull request closed without merging**
