### PR TITLE
techcobweb-1266-local-build-obr-change

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

- [x] Local builds pick up OBR from different location
- [x] Ignore failing junit tests until we make them work with issue #1250
- [x] minor javadoc corrections

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by techcobweb** [comment]
Comments from Caroline:
Hi, for 194, I spotted a couple of tiny typos - there is still a registrtion lurking and also you have "A map of key, value pairs" which I think should be "A map of key-value pairs".  I assume that the inheritDoc annotation is a simplification of what is there. I am just checking my notes regarding the change to the license wording but assuming it is what Gary Bettesworth said it should be.

**Comment by techcobweb** [comment]
Changes for spelling and key-value pair pushed.

**Comment by techcobweb** [comment]
The inheritdoc is far less likely to create a broken link. In fact, even that isn't required, as inheriting the doc is done by default anyway, but it does make it explicit, and deleting the entire javadoc seemed to brutal a change for now.

**Comment by galasa-team** [comment]
Build successful

**Review by CaroMac — APPROVED** [review]

**Pull request merged**
