### PR TITLE
Iss1768

### PR DESCRIPTION
**Pull request by jadecarino**
## Why?

For story https://github.com/galasa-dev/projectmanagement/issues/1768

- Creation of new Galasa extension - a Kafka plugin
- Add the new extension into the local build process with code coverage report
- Classes to register the Events Service with the OSGi whiteboard pattern
- Events Service to produce events and shutdown the producers
- Event Producer Factory to create an Event Producer in a unit-testable way
- Event Producer to actually publish events to a Kafka topic using the Kafka libraries
- Unit tests for the Events Service and Registration and mock classes
- Add the new Galasa extension to the release.yaml so it's shipped in the next release

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by KirbyKatcher — APPROVED** [review]

**Pull request merged**
